// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var breadcrumb, checkIfActive, down, menuLink, target, textBox, up;
    breadcrumb = $('.breadcrumb');
    textBox = $('textarea');
    target = 'body';
    textBox.focus(function() {
      $('.menu').addClass('inactive');
      $(this).parent().parent().addClass('focused');
      $(this).parent().addClass('currently-focused');
      return checkIfActive();
    });
    textBox.blur(function() {
      $('.menu').removeClass('inactive');
      $(this).parent().parent().removeClass('focused');
      $(this).parent().removeClass('currently-focused');
      return checkIfActive();
    });
    menuLink = $('.menu a');
    menuLink.click(function(e) {
      var breadcrumbText;
      e.preventDefault();
      $(this).parent().parent().parent().parent().addClass('inactive');
      breadcrumbText = $(this).text();
      breadcrumb.html(breadcrumbText);
      $("html, body").animate({
        scrollTop: $(target).offset().top
      }, "easeInOutExpo");
      $('#html').focus();
      return checkIfActive();
    });
    checkIfActive = function() {
      if ($('.inactive').length === 0) {
        breadcrumb.removeClass('bounceInUp');
        return breadcrumb.addClass('bounceOutUp');
      } else {
        breadcrumb.removeClass('bounceOutUp');
        return breadcrumb.addClass('bounceInUp');
      }
    };
    up = 38;
    down = 40;
    document.onkeydown = function(e) {
      switch (e.keyCode) {
        case down:
          $('.menu').removeClass('inactive');
          return checkIfActive();
        case up:
          $('.menu').addClass('inactive');
          $("html, body").animate({
            scrollTop: $(target).offset().top
          }, "easeInOutExpo");
          return checkIfActive();
      }
    };
    return $(window).scroll(function() {
      var scroll;
      scroll = $(window).scrollTop();
      if (scroll < 0) {
        $('.menu').removeClass('inactive');
        return checkIfActive();
      }
    });
  });

}).call(this);
