// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var textBox;
    textBox = $('textarea');
    textBox.focus(function() {
      $('.menu').addClass('inactive');
      $(this).parent().parent().addClass('focused');
      return $(this).parent().addClass('currently-focused');
    });
    return textBox.blur(function() {
      $('.menu').removeClass('inactive');
      $(this).parent().parent().removeClass('focused');
      return $(this).parent().removeClass('currently-focused');
    });
  });

}).call(this);
